//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication2._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActionInfo
    {
        public ActionInfo()
        {
            this.DepartmentsBackups = new HashSet<DepartmentsBackup>();
            this.EmployeesBackups = new HashSet<EmployeesBackup>();
            this.TeamsBackups = new HashSet<TeamsBackup>();
        }
    
        public int IdAction { get; set; }
        public Nullable<int> ResponsableAction { get; set; }
        public Nullable<int> TypeAction { get; set; }
        public Nullable<System.DateTime> DateAction { get; set; }
    
        public virtual ICollection<DepartmentsBackup> DepartmentsBackups { get; set; }
        public virtual ICollection<EmployeesBackup> EmployeesBackups { get; set; }
        public virtual ICollection<TeamsBackup> TeamsBackups { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
