//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication2._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepartmentsBackup
    {
        public int Id { get; set; }
        public int Id_Dept { get; set; }
        public string Nombre_Dept { get; set; }
        public string Name { get; set; }
        public string Correo { get; set; }
        public Nullable<int> ActionInfo { get; set; }
    
        public virtual ActionInfo ActionInfo1 { get; set; }
    }
}
