//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication2._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeeklyReportsState
    {
        public WeeklyReportsState()
        {
            this.WeeklyReportsDetails = new HashSet<WeeklyReportsDetail>();
        }
    
        public int Id { get; set; }
        public int StateReport { get; set; }
        public decimal PercentReports { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public int TypeError { get; set; }
    
        public virtual ICollection<WeeklyReportsDetail> WeeklyReportsDetails { get; set; }
    }
}
