//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication2._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeeklyReportsDetail
    {
        public int Id { get; set; }
        public int TypeReport { get; set; }
        public int IdReceptor { get; set; }
        public int StateReport { get; set; }
        public int TypeError { get; set; }
        public int IdWeeklyReportState { get; set; }
    
        public virtual WeeklyReportsState WeeklyReportsState { get; set; }
    }
}
